// Generated by https://quicktype.io
package identify

type MagickResult []MagickJson

type MagickJson struct {
	Version string `json:"version"`
	Image   Image  `json:"image"`
}

type Image struct {
	Name              string            `json:"name"`
	BaseName          string            `json:"baseName"`
	Format            string            `json:"format"`
	FormatDescription string            `json:"formatDescription"`
	MIMEType          string            `json:"mimeType"`
	Class             string            `json:"class"`
	Geometry          Geometry          `json:"geometry"`
	Resolution        PrintSize         `json:"resolution"`
	PrintSize         PrintSize         `json:"printSize"`
	Units             string            `json:"units"`
	Type              string            `json:"type"`
	BaseType          string            `json:"baseType"`
	Endianness        string            `json:"endianness"`
	Colorspace        string            `json:"colorspace"`
	Depth             int64             `json:"depth"`
	BaseDepth         int64             `json:"baseDepth"`
	ChannelDepth      ChannelDepth      `json:"channelDepth"`
	Pixels            int64             `json:"pixels"`
	ImageStatistics   ImageStatistics   `json:"imageStatistics"`
	ChannelStatistics ChannelStatistics `json:"channelStatistics"`
	RenderingIntent   string            `json:"renderingIntent"`
	Gamma             float64           `json:"gamma"`
	Chromaticity      Chromaticity      `json:"chromaticity"`
	MatteColor        string            `json:"matteColor"`
	BackgroundColor   string            `json:"backgroundColor"`
	BorderColor       string            `json:"borderColor"`
	TransparentColor  string            `json:"transparentColor"`
	Interlace         string            `json:"interlace"`
	Intensity         string            `json:"intensity"`
	Compose           string            `json:"compose"`
	PageGeometry      Geometry          `json:"pageGeometry"`
	Dispose           string            `json:"dispose"`
	Iterations        int64             `json:"iterations"`
	Compression       string            `json:"compression"`
	Quality           int64             `json:"quality"`
	Orientation       string            `json:"orientation"`
	Properties        map[string]string `json:"properties"`
	Profiles          Profiles          `json:"profiles"`
	Tainted           bool              `json:"tainted"`
	Filesize          string            `json:"filesize"`
	NumberPixels      string            `json:"numberPixels"`
	PixelsPerSecond   string            `json:"pixelsPerSecond"`
	UserTime          string            `json:"userTime"`
	ElapsedTime       string            `json:"elapsedTime"`
	Version           string            `json:"version"`
}

type ChannelDepth struct {
	Red   int64 `json:"red"`
	Green int64 `json:"green"`
	Blue  int64 `json:"blue"`
}

type ChannelStatistics struct {
	Red   Blue `json:"red"`
	Green Blue `json:"green"`
	Blue  Blue `json:"blue"`
}

type Blue struct {
	Min               int64   `json:"min"`
	Max               int64   `json:"max"`
	Mean              float64 `json:"mean"`
	Median            float64 `json:"median"`
	StandardDeviation float64 `json:"standardDeviation"`
	Kurtosis          float64 `json:"kurtosis"`
	Skewness          float64 `json:"skewness"`
	Entropy           float64 `json:"entropy"`
}

type Chromaticity struct {
	RedPrimary   PrintSize `json:"redPrimary"`
	GreenPrimary PrintSize `json:"greenPrimary"`
	BluePrimary  PrintSize `json:"bluePrimary"`
	WhitePrimary PrintSize `json:"whitePrimary"`
}

type PrintSize struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type Geometry struct {
	Width  int64 `json:"width"`
	Height int64 `json:"height"`
	X      int64 `json:"x"`
	Y      int64 `json:"y"`
}

type ImageStatistics struct {
	Overall Blue `json:"Overall"`
}

type Profiles struct {
	The8Bim The8_Bim `json:"8bim"`
	Icc     The8_Bim `json:"icc"`
	Iptc    Iptc     `json:"iptc"`
}

type The8_Bim struct {
	Length int64 `json:"length"`
}

type Iptc struct {
	City190        []string      `json:"City[1,90]"`
	Unknown20      []interface{} `json:"Unknown[2,0]"`
	CreatedDate255 []string      `json:"Created Date[2,55]"`
	CreatedTime260 []string      `json:"Created Time[2,60]"`
	Unknown262     []string      `json:"Unknown[2,62]"`
	Unknown263     []string      `json:"Unknown[2,63]"`
	Byline280      []string      `json:"Byline[2,80]"`
	Caption2120    []string      `json:"Caption[2,120]"`
	Length         int64         `json:"length"`
}
